from pydantic import BaseModel, Field
from typing import Annotated, Literal
from operator import add

# --------- Stateful Agent Schema ---------

class AgentSchema(BaseModel):
    messages: Annotated[list, add] = Field(..., description="A list of messages exchanged between the user and the agent.")
    user_question: str = Field(..., description="The input provided by the user to the agent.")
    curated_question: str = Field(..., description="A curated question that the agent will use to generate a response.")
    prompt_query_context: str = Field(..., description="A detailed prompt with SQL DB context to help the agent generate SQL query.")
    generated_sql_query: str = Field(..., description="The SQL query generated by the agent based on the curated question and prompt context.")
    is_safe: bool = Field(..., description="A boolean (by the judge) indicating whether the agent's response is safe or not.")
    comments: str = Field(..., description="Comments or feedback provided by the judge regarding the generated SQL query.")
    sql_query_result: str = Field(..., description="The result of executing the generated SQL query against the database.")
    final_response: str = Field(..., description="The final response generated by the agent after processing the SQL query result and other relevant information.")
    
    
class JudgeSchema(BaseModel):
    answer: bool = Field(..., description="A boolean indicating whether the agent's response is safe or not.")
    comments: str = Field(..., description="Comments or feedback provided by the judge regarding the agent's response.")
    
    
# --------- ReAct Agent Schema ---------

class ETLAgentSchema(BaseModel):
    messages: Annotated[list, add] = Field(..., description="A list of messages exchanged between the user and the ETL agent.")
    
    
# --------- Parent Agent Schema ---------    

class ParentAgentSchema(BaseModel):
    messages: Annotated[list, add] = Field(..., description="Message history to be accessed by the Data Agent.")
    answer: str = Field("", description="The agent selected to handle the question ('sql' or 'etl').")
    comments: str = Field("", description="Comments from the agent selection step.")



# --------- Agent Selection Schema ---------
  
class AgentSelectionSchema(BaseModel):
    answer: Literal['sql', 'etl'] = Field(..., description="The type of agent that should handle the user's question. It can be either 'sql' for SQL Agent or 'etl' for ETL Agent.")
    comments: str = Field(..., description="Comments or feedback provided by the parent agent regarding the decision made.")
    
    
    